### ISSUE TITLE
libsass problem

### ISSUE THREAD

**Issue by universalien** [djett41/ionic-scroll-sista#31]
```
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`?');
    ^

    Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (C:\...\ionic-scroll-sista\node_modules\node-sass\lib\index.js:22:11)
    at Object.<anonymous> (C:\...\ionic-scroll-sista\node_modules\node-sass\lib\index.js:188:23)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (C:\...\ionic-scroll-sista\node_modules\gulp-sass\index.js:3:17)
    at Module._compile (module.js:399:26)

    npm ERR! Windows_NT 6.3.9600
    npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "gulp"
    npm ERR! node v5.2.0
    npm ERR! npm  v3.3.12
    npm ERR! code ELIFECYCLE
    npm ERR! demo@1.0.0 gulp: `gulp`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the demo@1.0.0 gulp script 'gulp'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the demo package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     gulp
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls demo
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     C:\...\ionic-scroll-sista\npm-debug.log
```

reinstalling `node-sass` is not solving the problem.

**Comment by universalien** [comment]
npm install node-sass@2.1 --save-dev
